//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichTuVan
    {
        public string MaTuVan { get; set; }
        public Nullable<System.DateTime> NgayGio { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string TinhTrang { get; set; }
        public string MaBS { get; set; }
        public string MaKH { get; set; }
    
        public virtual BACSI BACSI { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
